"""The gate framework (docs/qc_workflow.md): one language for every gate's verdicts, flags and
advice; the QC log of a run; retry budgets; the configuration of thresholds and budgets. The gates
G1 to G6 (milestones 11 to 13), the coherence rules for S2 and the checks before S4, a line
processed and inverted the QC way, and the stages done again."""

from .attempts import ATTEMPTS_FOLDER, STAGE_FILES, archived_attempts, downstream, invalidate
from .budgets import budget_spent, can_retry, run_budget
from .coherence import (
    CoherenceRules,
    LengthChoice,
    LengthTrial,
    cap_band,
    choose_length,
    describe_lengths,
    given_length,
    read_length_choice,
)
from .config import CONFIG_FILE, QCConfig, load_qc_config, read_qc_config, snapshot_qc_config
from .curves import pick_line, settle_curves
from .g3_curve import CurveThresholds
from .g4_profile import LINE, ProfileThresholds, judge_profile
from .g5_model import ModelThresholds, judge_model
from .g6_models import ModelProfileThresholds, judge_model_profile
from .inverting import (
    MEASURES_FILE,
    invertible,
    judge_inversions,
    judge_model_line,
    rerun_inversion,
    run_inversion_job,
    settle_models,
    submit_inversion,
)
from .judging import judge_line, judge_picking, judge_records, judge_run, judge_windows
from .line import process_line, settle_images, settle_records
from .log import (
    LOG_FILE,
    append_attempt,
    attempts_of,
    ensure_initial_attempts,
    latest,
    read_attempts,
    record_result,
    retries_at_gate,
    retries_by_unit,
    retries_in_run,
)
from .models import (
    STAGES,
    Action,
    Attempt,
    Budgets,
    ExcludeRecord,
    ExcludeTraces,
    Flag,
    GateResult,
    Keep,
    Kept,
    Metric,
    Override,
    Reject,
    Stage,
    Verdict,
    stage_index,
)
from .priors import Derived, PriorRules, derive_inversion
from .redo import check_budget, redo_stage, select_windows
from .report import (
    REPORT_FILE,
    QCReport,
    StageResult,
    UnitReport,
    build_report,
    changed_settings,
    describe,
    read_report,
    stretches,
    summarize_report,
    write_report,
    xmid_of,
)
from .rerun import rerun_phase_shift, rerun_picking
from .sides import Series

__all__ = [
    "ATTEMPTS_FOLDER",
    "CONFIG_FILE",
    "LINE",
    "LOG_FILE",
    "MEASURES_FILE",
    "REPORT_FILE",
    "STAGES",
    "STAGE_FILES",
    "Action",
    "Attempt",
    "Budgets",
    "CoherenceRules",
    "CurveThresholds",
    "Derived",
    "ExcludeRecord",
    "ExcludeTraces",
    "Flag",
    "GateResult",
    "Keep",
    "Kept",
    "LengthChoice",
    "LengthTrial",
    "Metric",
    "ModelProfileThresholds",
    "ModelThresholds",
    "Override",
    "PriorRules",
    "ProfileThresholds",
    "QCConfig",
    "QCReport",
    "Reject",
    "Series",
    "Stage",
    "StageResult",
    "UnitReport",
    "Verdict",
    "append_attempt",
    "archived_attempts",
    "attempts_of",
    "budget_spent",
    "build_report",
    "can_retry",
    "cap_band",
    "changed_settings",
    "check_budget",
    "choose_length",
    "derive_inversion",
    "describe",
    "describe_lengths",
    "downstream",
    "ensure_initial_attempts",
    "given_length",
    "invalidate",
    "invertible",
    "judge_inversions",
    "judge_line",
    "judge_model",
    "judge_model_line",
    "judge_model_profile",
    "judge_picking",
    "judge_profile",
    "judge_records",
    "judge_run",
    "judge_windows",
    "latest",
    "load_qc_config",
    "pick_line",
    "process_line",
    "read_attempts",
    "read_length_choice",
    "read_qc_config",
    "read_report",
    "record_result",
    "redo_stage",
    "rerun_inversion",
    "rerun_phase_shift",
    "rerun_picking",
    "retries_at_gate",
    "retries_by_unit",
    "retries_in_run",
    "run_budget",
    "run_inversion_job",
    "select_windows",
    "settle_curves",
    "settle_images",
    "settle_models",
    "settle_records",
    "snapshot_qc_config",
    "stage_index",
    "stretches",
    "submit_inversion",
    "summarize_report",
    "write_report",
    "xmid_of",
]
